# Database
#AWS Dev
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/mahaexam?zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username: root
spring.datasource.password: Rootpwd@1234

spring.mail.from=info@eduval.in
cors.allowed-origins=http://localhost:4201,http://3.110.16.23,http://3.110.16.23/MahaExam,https://3.110.16.23/MahaExam,https://3.110.16.23,http://3.110.16.23,http://localhost:4201,http://13.127.50.157,http://13.127.50.157/MahaExam,https://13.127.50.157/MahaExam,https://13.127.50.157,http://13.127.50.157,,https://mahaexam.org.in,http://mahaexam.org.in

# Spring Cloud AWS SQS Configuration for DEV
# Credentials are provided via system properties: -Daws.accessKeyId= -Daws.secretAccessKey= -Daws.accountId=
# Queue created manually: mahaexam-exam-dev-queue
spring.cloud.aws.sqs.enabled=true
spring.cloud.aws.sqs.endpoint=https://sqs.ap-south-1.amazonaws.com
spring.cloud.aws.sqs.listener.queue-not-found-strategy=fail
spring.cloud.aws.sqs.listener.queue-creation-strategy=never
spring.cloud.aws.sqs.listener.auto-startup=false


app.aws.sqs.exam-queue=https://sqs.ap-south-1.amazonaws.com/${aws.accountId:805472282650}/mahaexam-exam-dev-queue

question.image.s3.bucket=dev-mahaexam-question-images
