# Database
#AWS Dev
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/mahaexam?zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username: root
spring.datasource.password: Rootpwd@1234


spring.mail.from=info@eduval.in