# ===============================
# = DATA SOURCE (PostgreSQL)
# ===============================

spring.application.name=User Service
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=Hamilton@44
spring.datasource.driver-class-name=org.postgresql.Driver
eureka.client.service-url.defaultZone= http://localhost:8761/eureka/
# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update