--liquibase formatted sql
--changeset {narendra}:{id}

-- mdeeper_dev83.education_society definition

CREATE TABLE `education_society` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `society_name` varchar(245) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted` enum('1','0') NOT NULL DEFAULT '0',
  `is_disabled` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28864 DEFAULT CHARSET=utf8;


CREATE TABLE `institutes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `index_number` varchar(40) DEFAULT '00.00.000',
  `udi_number` varchar(40) DEFAULT NULL,
  `institute_name` varchar(245) DEFAULT NULL,
  `institute_addess_line_1` varchar(250) DEFAULT NULL,
  `institute_addess_line_2` varchar(250) DEFAULT NULL,
  `place` varchar(80) DEFAULT NULL,
  `latitude` text,
  `longitude` text,
  `pin_code` varchar(11) DEFAULT NULL,
  `telephone` varchar(20) DEFAULT NULL,
  `mobile_number` varchar(20) DEFAULT NULL,
  `email_id` varchar(85) DEFAULT NULL,
  `intake_capacity` varchar(45) DEFAULT NULL,
  `intake_capacity_12th` varchar(45) DEFAULT NULL,
  `staff_details` varchar(250) DEFAULT NULL,
  `digi_infra_availability` varchar(50) DEFAULT NULL,
  `batches` varchar(50) DEFAULT NULL,
  `special_batch_staff_availability` varchar(50) DEFAULT NULL,
  `seating_strength_offline_online` varchar(45) DEFAULT NULL,
  `on_off_center_availability` varchar(50) DEFAULT NULL,
  `online_exam_availability` varchar(45) DEFAULT NULL,
  `offline_exam_availability` varchar(45) DEFAULT NULL,
  `seating_strength_offline` varchar(45) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted` enum('1','0') NOT NULL DEFAULT '0',
  `edu_society_id` int(11) DEFAULT NULL,
  `taluka_id` int(11) DEFAULT NULL,
  `state_id` int(11) DEFAULT NULL,
  `district_id` int(11) DEFAULT NULL,
  `division_id` int(11) DEFAULT NULL,
  `zone_id` int(11) DEFAULT NULL,
  `power_backup` varchar(10) DEFAULT NULL,
  `digital_infrastructure_availability` varchar(500) DEFAULT NULL,
  `non_teaching_staff` varchar(45) DEFAULT NULL,
  `staff_availability_physics` varchar(250) DEFAULT NULL,
  `staff_availability_chemistry` varchar(250) DEFAULT NULL,
  `staff_availability_botney` varchar(250) DEFAULT NULL,
  `staff_availability_zoology` varchar(250) DEFAULT NULL,
  `staff_availability_math` varchar(250) DEFAULT NULL,
  `distinction` varchar(40) DEFAULT NULL,
  `total_intake` varchar(40) DEFAULT NULL,
  `status` varchar(15) DEFAULT 'pending',
  `token_id` varchar(40) DEFAULT NULL,
  `is_disabled` tinyint(1) DEFAULT '0',
  `institute_discount` varchar(100) DEFAULT NULL,
  `center_level` enum('1','2','3','4') DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `taluka_id` (`taluka_id`),
  KEY `state_id` (`state_id`),
  KEY `district_id` (`district_id`),
  KEY `division_id` (`division_id`),
  KEY `edu_society_id` (`edu_society_id`),
  KEY `token_id` (`token_id`),
  KEY `fk_institutes_zone` (`zone_id`),
  CONSTRAINT `fk_institutes_zone` FOREIGN KEY (`zone_id`) REFERENCES `zone` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `in_district_id_fk` FOREIGN KEY (`district_id`) REFERENCES `district` (`id`),
  CONSTRAINT `in_edu_society_id_fk` FOREIGN KEY (`edu_society_id`) REFERENCES `education_society` (`id`),
  CONSTRAINT `in_division_id_fk` FOREIGN KEY (`division_id`) REFERENCES `division` (`id`),
  CONSTRAINT `in_state_id_fk` FOREIGN KEY (`state_id`) REFERENCES `state` (`id`),
  CONSTRAINT `in_taluka_id_fk` FOREIGN KEY (`taluka_id`) REFERENCES `taluka` (`id`)
) ENGINE=InnoDB;