package com.mahaexam.question.controller;

import com.mahaexam.common.bean.UserBean;
import com.mahaexam.common.controller.BaseController;
import com.mahaexam.common.exception.ValidationException;
import com.mahaexam.openai.model.QuestionMetadata;
import com.mahaexam.openai.model.QuestionSet;
import com.mahaexam.question.model.QuestionEntity;
import com.mahaexam.question.service.QuestionService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * REST Controller for question management
 */
@RestController
@RequestMapping("/api/questions")
public class QuestionController extends BaseController {

    private static final Logger logger = LoggerFactory.getLogger(QuestionController.class);

    private final QuestionService questionService;

    public QuestionController(QuestionService questionService) {
        this.questionService = questionService;
    }

    /**
     * Save a question set generated by AI
     */
    @PostMapping("/save-set")
    public ResponseEntity<List<QuestionEntity>> saveQuestionSet(
            @RequestBody QuestionSet questionSet) {
        UserBean user = getUser();
        List<QuestionEntity> savedQuestions = questionService.saveQuestionSet(questionSet, user);
        return ResponseEntity.status(HttpStatus.CREATED).body(savedQuestions);
    }

    /**
     * Get questions by various filters
     */
    @GetMapping("/search")
    public ResponseEntity<List<QuestionEntity>> searchQuestions(
            @RequestParam(required = false) Integer boardId,
            @RequestParam(required = false) Integer classId,
            @RequestParam(required = false) Integer subjectId,
            @RequestParam(required = false) Integer topicId,
            @RequestParam(required = false) String questionType,
            @RequestParam(required = false) String skillLevel,
            @RequestParam(required = false) String difficultyLevel) {

        List<QuestionEntity> questions = questionService.findQuestions(
                boardId, classId, subjectId, topicId, questionType, skillLevel, difficultyLevel);
        return ResponseEntity.ok(questions);
    }

    /**
     * Get a single question by ID
     */
    @GetMapping("/{id}")
    public ResponseEntity<QuestionEntity> getQuestionById(@PathVariable Long id) {
        QuestionEntity question = questionService.getQuestionById(id);
        if (question == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(question);
    }

    /**
     * Delete a question by ID
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteQuestion(@PathVariable Long id) {
        boolean deleted = questionService.deleteQuestion(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }

    /**
     * Check if questions with same prompt already exist
     */
    @GetMapping("/check-duplicate")
    public ResponseEntity<Boolean> checkDuplicate(@RequestParam String aiPromptHash) {
        boolean exists = questionService.isDuplicatePrompt(aiPromptHash);
        return ResponseEntity.ok(exists);
    }

    /**
     * Generate questions using OpenAI based on metadata and save to database
     *
     */
    @PostMapping("/generate-and-save")
    public ResponseEntity<?> generateAndSaveQuestions(
            @RequestBody QuestionMetadata metadata) {

        try {
            // Validate: paragraph-based questions must be in multiples of 5
            if (metadata.getQuestionType() != null
                    && metadata.getQuestionType().toLowerCase().contains("paragraph")
                    && metadata.getNumberOfQuestions() != null
                    && metadata.getNumberOfQuestions() % 5 != 0) {
                throw new ValidationException(
                        "For paragraph-based questions, the number of questions must be a multiple of 5 (e.g., 5, 10, 15). " +
                        "Each paragraph generates exactly 5 questions. Requested: " + metadata.getNumberOfQuestions());
            }

            UserBean user = getUser();
            List<QuestionEntity> savedQuestions = questionService.generateAndSaveQuestions(metadata, user);
            return ResponseEntity.status(HttpStatus.CREATED).body(savedQuestions);
        } catch (IllegalArgumentException e) {
            logger.warn(e.getMessage());
            throw new ValidationException(e.getMessage());
        } catch (java.util.concurrent.CompletionException ce) {
            // Unwrap the real cause for a meaningful log + response
            Throwable rootCause = ce.getCause() != null ? ce.getCause() : ce;
            logger.error("Error generating and saving questions — root cause: {}", rootCause.getMessage(), rootCause);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error: " + rootCause.getMessage());
        } catch (Exception e) {
            logger.error("Error generating and saving questions", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error: " + e.getMessage());
        }
    }

    /**
     * Generate random questions as PDF with answers and explanations
     * Accepts QuestionMetadata with names to avoid additional DB calls
     */
    @PostMapping("/random-pdf")
    public ResponseEntity<byte[]> getRandomQuestionsPdf(
            @RequestBody QuestionMetadata metadata) {

        try {
            // Get current user
            UserBean user = getUser();

            // Set default number of questions if not provided
            if (metadata.getNumberOfQuestions() == null) {
                metadata.setNumberOfQuestions(10);
            }

            byte[] pdfBytes = questionService.getRandomQuestionsAsPdf(metadata, user);

            return ResponseEntity.ok()
                    .header("Content-Type", "application/pdf")
                    .header("Content-Disposition", "attachment; filename=questions.pdf")
                    .body(pdfBytes);
        } catch (IllegalArgumentException | IllegalStateException e) {
            logger.warn(e.getMessage());
            throw new ValidationException(e.getMessage());
        } catch (Exception e) {
            logger.error("Error generating PDF", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Generate questions for each topic of a given chapter
     * This endpoint fetches all topics for the specified chapter and generates
     * the specified number of questions for each topic automatically.
     *
     * Request Body (QuestionMetadata):
     * - boardId: Board ID (required)
     * - classId: Class ID (required)
     * - subjectId: Subject ID (required)
     * - chapterId: Chapter ID (required)
     * - numberOfQuestions: Number of questions per topic (required)
     * - medium: Medium of instruction (required, e.g., "English", "Hindi")
     * - questionType: Type of questions (optional, defaults to "MCQ")
     * - skillLevel: Skill level (optional, defaults to "Intermediate")
     * - difficulty: Difficulty level (optional, defaults to "Medium")
     *
     * @return Map of topic ID to list of generated questions
     **/

    @PostMapping("/generate/chapter-topics")
    public ResponseEntity<?> generateQuestionsForChapterTopics(@RequestBody QuestionMetadata metadata
           ) {
        Integer boardId  = metadata.getBoardId();
        Integer classId = metadata.getClassId();
        Integer subjectId = metadata.getSubjectId();
        Integer chapterId = metadata.getChapterId();
        Integer noOfQuestionsPerTopic = metadata.getNumberOfQuestions();
        String medium = metadata.getMedium();
        String questionType = metadata.getQuestionType() != null ? metadata.getQuestionType() : "MCQ";
        String skillLevel = metadata.getSkillLevel() != null ? metadata.getSkillLevel() : "Intermediate";
        String difficulty = metadata.getDifficulty() != null ? metadata.getDifficulty() : "Medium";

        try {
            logger.info("Request to generate {} {} questions per topic for Chapter ID: {}, Board: {}, Class: {}, Subject: {}, Medium: {}, SkillLevel: {}, Difficulty: {}",
                    noOfQuestionsPerTopic, questionType, chapterId, boardId, classId, subjectId, medium, skillLevel, difficulty);

            // Get current user from session
            UserBean user = getUser();

            // Validate input parameters
            if (noOfQuestionsPerTopic <= 0) {
                throw new ValidationException("Number of questions per topic must be greater than 0");
            }

            // Validate: paragraph-based questions must be in multiples of 5
            if (questionType.toLowerCase().contains("paragraph") && noOfQuestionsPerTopic % 5 != 0) {
                throw new ValidationException(
                        "For paragraph-based questions, the number of questions must be a multiple of 5 (e.g., 5, 10, 15). " +
                        "Each paragraph generates exactly 5 questions. Requested: " + noOfQuestionsPerTopic);
            }

            if (medium == null || medium.trim().isEmpty()) {
                throw new ValidationException("Medium is required");
            }

            if (boardId == null || classId == null || subjectId == null || chapterId == null) {
                throw new ValidationException("boardId, classId, subjectId, and chapterId are required");
            }

            // Call service to generate questions for all topics in the chapter
            Map<Integer, List<QuestionEntity>> topicQuestionsMap =
                    questionService.generateQuestionsForChapterTopics(
                            metadata, user);

            // Calculate statistics
            int totalTopics = topicQuestionsMap.size();
            int totalQuestions = topicQuestionsMap.values().stream()
                    .mapToInt(List::size)
                    .sum();

            logger.info("Successfully generated {} {} questions for {} topics, total {} questions",
                    questionType, noOfQuestionsPerTopic, totalTopics, totalQuestions);

            // Return the map with topic IDs and their questions
            return ResponseEntity.status(HttpStatus.CREATED).body(topicQuestionsMap);

        } catch (IllegalArgumentException e) {
            logger.warn("Validation error: {}", e.getMessage());
            throw new ValidationException(e.getMessage());
        } catch (IllegalStateException e) {
            logger.error("State error: {}", e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error: " + e.getMessage());
        } catch (Exception e) {
            logger.error("Error generating questions for chapter topics", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error generating questions: " + e.getMessage());
        }
    }
}
